import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Online Shopping site in India",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  model
}: Readonly<{
  children: React.ReactNode;
  model: React.ReactNode;
}>) {
  return (
    <div>
        {model}
        {children}
    </div>
  );
}
